### ISSUE TITLE
After adding this plugin my project stops working...

### ISSUE THREAD

**Issue by rodrigograca31** [jcesarmobile/plusOneButtonPlugin#1]
The CLI log:

```
:compileDebugSources
:transformClassesWithDexForDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/actions/ReserveIntents;
    at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
    at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
    at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
    at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
    at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
    at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
    at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
    at com.android.dx.command.dexer.Main.run(Main.java:277)
    at com.android.dx.command.dexer.Main.main(Main.java:245)
    at com.android.dx.command.Main.main(Main.java:106)


 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-7-openjdk-amd64/bin/java'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

```

**Comment by jcesarmobile** [comment]
Can you list the plugins and versions you have installed? looks like one of them is using an outdated way to declare dependencies

**Comment by rodrigograca31** [comment]
@jcesarmobile I had this problem before and `cordova platform rm android` and `cordova platform add android` solved it, but now it's complaining:

```
Failed to install 'cordova-plugin-google-analytics':CordovaError: Failed to fetch plugin cordova-plugin-googleplayservices@19.0.0 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.

```

I solved it by removing `@19.0.0` from the plugin.xml file of that plugin and I will ask them to do it....

**Comment by jcesarmobile** [comment]
I answered on the issue you opened there.
So it the problem fixed?

**Comment by rodrigograca31** [comment]
I think it's almost there.... after I removed all the plugins and added them again 20 times....

**Comment by rodrigograca31** [comment]
I still have some kind of conflict even after removing this plugin.... 

```
:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> Error: more than one library with package name 'com.google.android.gms'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by jcesarmobile** [comment]
The problem is your admob plugin because it adds the cordova-google-play-services as dependency, and that plugin is the one making this problem appear.

Which plugin are you using for admob?

**Comment by rodrigograca31** [comment]
I was using the old admob now right now I'm usign admob pro, I removed it and analytics (also used the play services) and removed every mention of play services in the dependencies/etc and added admob pro and it's working.... 

Now I need to add the analytics plugin....

**Comment by rodrigograca31** [comment]
just run `cordova plugin add cordova-plugin-google-analytics` and it worked....
seems thats solved... I just need to make sure I didn't forgot any plugin, then add this one and it's done!

**Comment by jcesarmobile** [comment]
Cool.
A lot of plugins need to be updated to use framework instead of dependency, if you have problems with others keep opening issues.

**Comment by rodrigograca31** [comment]
Yes, I learned that... I had to remove everything that I had not touched in months and add it again....
