### ISSUE TITLE
Placing the Code.

### ISSUE THREAD

**Issue by Vhiktordom** [jcesarmobile/plusOneButtonPlugin#12]
Hello, thanks for creating this plugin, it's a big solution to many other out there, Please where do I place the  plusOneButton.show("http://www.example.com"); 
code in my ionic project.
Sorry if the question seem too stupid, I'm just learning how to use the framework.

**Comment by rodrigograca31** [comment]
You place it in the controller that is associated with the view where you want to show the button....
so that when the view is shown the controller executes and shows the button

**Comment by jcesarmobile** [comment]
I think @rodrigograca31 answer is good, closing the issue.
