### ISSUE TITLE
It disappears when an ad loads

### ISSUE THREAD

**Issue by rodrigograca31** [jcesarmobile/plusOneButtonPlugin#2]
I noticed that it shows up and when the ad that my has at the bottom loads (1 or 2 seconds later) the +1 button disappears.... As if it had a "z-index" and it changed or as if his view was replaced by the ad view at the bottom....

**Comment by jcesarmobile** [comment]
If you tell me the admob plugin you use (the id, not the name) I can try to take a look

**Comment by rodrigograca31** [comment]
The admob plugin id: `cordova-plugin-admobpro` 
[https://github.com/floatinghotpot/cordova-admob-pro](https://github.com/floatinghotpot/cordova-admob-pro)

**Comment by rodrigograca31** [comment]
The ad configs:

```
window.AdMob.createBanner({
    adId: "MY private ID",
    position: AdMob.AD_POSITION.BOTTOM_CENTER,
    autoShow: true,
    adSize: 'SMART_BANNER'
});
```

**Comment by rodrigograca31** [comment]
I also have one interstitial ad and doesn't cause this problem....

**Comment by rodrigograca31** [comment]
Trying to use the success callback doesn't work, code:

```
window.AdMob.createBanner({
    adId: "FAKE-ID",
    position: AdMob.AD_POSITION.BOTTOM_CENTER,
    autoShow: true,
    adSize: 'SMART_BANNER',
    success: function(){
        console.log("plus");
        var params = {};
        params.url = "https://example.com";
        params.size = 2;
        params.annotation = 1;
        params.position = {x:100,y:100};
        plusOneButton.show(params);
    }
});
```

Also, when the ad is loaded I'm not able to show the +1 button from the chrome remote developer tools console.....but it works if there is no ad....

The admob pro plugin documentation: [https://github.com/floatinghotpot/cordova-admob-pro/tree/master/docs#admobcreatebanneradidoptions-success-fail](https://github.com/floatinghotpot/cordova-admob-pro/tree/master/docs#admobcreatebanneradidoptions-success-fail)

**Comment by jcesarmobile** [comment]
Thanks for the extra information, I'll look into it this weekend

**Comment by rodrigograca31** [comment]
Ok, maybe I should open another issue on the admob pro plugin repository? (They might know what is happening...)

**Comment by umesh25** [comment]
you have to add overlap:true in admob config;

```
AdMob.createBanner( {
        adId: admobid.banner, 
        isTesting: true,
        overlap: true, 
        offsetTopBar: false, 
        position: AdMob.AD_POSITION.BOTTOM_CENTER,
    });
```

i tested my self and its working properly.

**Comment by rodrigograca31** [comment]
@umesh25 you are right! Thank you!

Just a note: I had a problem before with the `overlap` option but I can't remember what it was... I just know that I had to change from `overlap: true` to `overlap: false` on the `window.AdMob.prepareInterstitial` function....

**Comment by rodrigograca31** [comment]
@umesh25 BTW, can you explain why this was happening? why did I need to specify the overlap option...?

**Comment by rodrigograca31** [comment]
I knew the `overlap` option would bring some problem.....
I noticed now that the ads apear over some of the app UI with `overlap: true` ....
I could give those elements a `margin-bottom` to make them visible but [according to the documentation](https://developers.google.com/admob/android/banner#banner_size) the "Smart Banner" has diferente heights....

**Comment by rodrigograca31** [comment]
Unfortunately now even with `overlap: true` this still happens.

**Comment by jcesarmobile** [comment]
And do you think it's something we changed or something the AdMob plugin changed?

**Comment by rodrigograca31** [comment]
Probably them... Since last time it was their problem....

**Comment by rodrigograca31** [comment]
I've left a comment there....

**Comment by jcesarmobile** [comment]
closing as the plugin is now deprecated
