### ISSUE TITLE
Some way to relocate/hide/show the button.

### ISSUE THREAD

**Issue by rodrigograca31** [jcesarmobile/plusOneButtonPlugin#4]
Since this is a native view over everything an app that uses this must have an always empty place...

This is not the case in my app, for example if I open the definitions it stays over them....

If there was a way to hide/show it I could manage that in the javascript code and make it work...

I tried to "re-run" the code but it creates a new button:

```
var params = {};
params.url = "https://example.com";
params.size = 2;
params.annotation = 1;
params.position = {x:500,y:500};
plusOneButton.show(params);
```

**Comment by rodrigograca31** [comment]
@jcesarmobile any ideas on how to implement this? Thanks!

**Comment by jcesarmobile** [comment]
Yeah, I have an idea. Will try it this afternoon.

**Comment by rodrigograca31** [comment]
@jcesarmobile Ok, thanks!

**Comment by jcesarmobile** [comment]
I've added a hide function, and show will draw it again isntead of creating a new one. 
Let me know if it works for you.

**Comment by rodrigograca31** [comment]
@jcesarmobile It's just me or you have not pushed your changes to this repo?

**Comment by jcesarmobile** [comment]
ahhhh, you are right, it pushed them to my local git, but forgot to push them to github. Sorry, I'll do it this afternoon.

**Comment by jcesarmobile** [comment]
Now it's published

**Comment by rodrigograca31** [comment]
Just looking at the code and noticed the "documentation" (README file) has a formatting problem.... 
(I will try the code later...)

**Comment by jcesarmobile** [comment]
fixed

**Comment by rodrigograca31** [comment]
Its working!
Thank you @jcesarmobile!
Did anyone ever told you that you are awesome?! :smile: 

(Maybe it's because you are from Spain! Hi, I'm from Portugal!) :smile:

**Comment by jcesarmobile** [comment]
Thanks for your words but I'm far from awesome. 
Thank you to for your PR.
Let me know if this is enough to show the button again when it is hidden by the admob add. 
If not I can try to destroy the button and add it again

**Comment by rodrigograca31** [comment]
Yhea, I still need to check that later, I was thinking in trying to see if the admob plugin had any callback and I would add the button after it loaded the add....
I will check it later....
