### ISSUE TITLE
A way to center it.

### ISSUE THREAD

**Issue by rodrigograca31** [jcesarmobile/plusOneButtonPlugin#5]
I was thinking I could a `div` 1px wide and then use:

``` javascript
position: {
    x: $(".div").offset().left,
    y: $(".div").offset().top
}
```

to place the +1 in the same place as that `div`... This didn't worked...
So, now I was trying to make it "full width" (`FILL_PARENT`) and centering it by changing line 85 from:

``` java
cordova.getActivity().addContentView(mPlusOneButton,new RelativeLayout.LayoutParams(RelativeLayout.LayoutParams.WRAP_CONTENT,RelativeLayout.LayoutParams.WRAP_CONTENT));
```

to

``` java
cordova.getActivity().addContentView(mPlusOneButton,new RelativeLayout.LayoutParams(RelativeLayout.LayoutParams.FILL_PARENT,RelativeLayout.LayoutParams.WRAP_CONTENT));
```

That works, but the +1 is not centered....
If we had the xml we could use:

``` xml
android:layout_centerHorizontal="true"
android:layout_centerInParent="true"
```

So, I got this working in android studio like this: (3rd line)

``` java
mPlusOneButton.setSize(PlusOneButton.SIZE_TALL);
mPlusOneButton.setAnnotation(PlusOneButton.ANNOTATION_BUBBLE);
((RelativeLayout.LayoutParams) mPlusOneButton.getLayoutParams()).addRule(RelativeLayout.CENTER_HORIZONTAL);
```

But I'm not able to make this work on this plugin.....

@jcesarmobile Any ideias?

**Comment by rodrigograca31** [comment]
I got it working by adding:

``` java
FrameLayout.LayoutParams params = (FrameLayout.LayoutParams) mPlusOneButton.getLayoutParams();
params.gravity = Gravity.CENTER;
mPlusOneButton.setLayoutParams(params);
```

after `mPlusOneButton.setAnnotation(annotation);` (line 91)
and adding two `imports`:

``` java
import android.widget.FrameLayout;
import android.view.Gravity;
```

Not sure if this is the best way to do it... (It's one way.... It works as I wanted it...)
@jcesarmobile Maybe this can be incorporate into the plugin as an option to center it? Or not?

**Comment by rodrigograca31** [comment]
Apparently it's not working on a Motorola G with Android Lollipop.....

**Comment by rodrigograca31** [comment]
Apparently commenting `mPlusOneButton.setX(x);` and `mPlusOneButton.setY(y);` solves the problem.....
It makes sense.....

**Comment by jcesarmobile** [comment]
closing as the plugin is now deprecated
