### ISSUE TITLE
Npm version is not up to date

### ISSUE THREAD

**Issue by rodrigograca31** [jcesarmobile/plusOneButtonPlugin#6]
Hi @jcesarmobile 

Not sure why but using the following command does not download the latest code...
`cordova plugin add cordova-plugin-plusonebutton --save`
or:
`npm i cordova-plugin-plusonebutton`

Maybe the `package.json` `version` key needs to be updated?

Best regards, Rodrigo Graça

**Comment by jcesarmobile** [comment]
I have published the new version on npm with latest changes

**Comment by rodrigograca31** [comment]
Hi @jcesarmobile Awesome!

You have to publish it on the npm "repo"??? (I've never published there)

I always thought npm was automatically getting it from the github repos....

**Comment by jcesarshit** [comment]
yes, from the plugin folder I did `npm publish .` and now the 1.0.1 appears on npm, so I think I have to manually publish when I make changes on github.

**Comment by jcesarmobile** [comment]
wops, commented from my test account.
