### ISSUE TITLE
Check if mPlusOneButton exits before hiding it.

### ISSUE THREAD

**Issue by rodrigograca31** [jcesarmobile/plusOneButtonPlugin#7]
The hide function should check if `mPlusOneButton` exists before setting it's visibility....

I know the right flow is to use `show()` then `hide()`, but for example, if I want to hide the button when the menu is open:

``` javascript
$scope.$watch(function () {
    return $ionicSideMenuDelegate.isOpen();
}, function (ratio) {
    if (ratio === true){
        window.plusOneButton.hide();
    } else{
        window.plusOneButton.show(params);
    }
});
```

This has a problem that is, if I setup the button on the controller, this function is executed before the `show()` and crashes the app... I'm guessing that it crashes because `mPlusOneButton` doesn't exists....

**Comment by rafaellop** [comment]
Fixed this and tested. PR done.

**Comment by rodrigograca31** [comment]
Thanks @rafaellop for your contribution! Looks ok!
@jcesarmobile could you merge it? Thanks!

**Comment by jcesarmobile** [comment]
merged
